### ISSUE TITLE
Apply changes in matchms

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#115]
Matchms has functionallity to automatically set the charge based on the ionmode, this is better to implement than the current solution of guessing the charge. 
Also a new option for selecting the retention time, can be used to get more reliable output from MS2Query

**Comment by florian-huber** [comment]
Should now be included in matchms 0.11.0

**Comment by niekdejonge** [comment]
The charge does not need to be set anymore, since precursor m/z is used instead of parent mass.

**Comment by florian-huber** [comment]
Should be fixed with #127
