### ISSUE TITLE
Add logging and remove confusing warnings

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#123]
When running MS2Query, the progress is returned with print statements. Adding logging would make sense. 

A lot of confusing print statements are currently printed. This should be changed, to make it less confusing for new users.
- Tensorflow errors should not be shown.
- Spec2Vecs prints a statement everytime a peak is not known, this should not be printed by default.

**Comment by florian-huber** [comment]
Spec2vec prints statements are gone now (switch to spec2vec>=0.6.0).

**Comment by niekdejonge** [comment]
closed with #166
