### ISSUE TITLE
Change numbering spectra MS2Query

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#134]
During preprocessing some spectra are removed (e.g. when they have less then 3 peaks). The spectrum number returned currently is the position in the cleaned list. The removed spectra are not numbered. This makes comparing results to other methods difficult, since this will result in different numbered spectra. 

Solution store scan number in the metadata and print this instead of the position in the list.

**Comment by justinjjvanderhooft** [comment]
Either that, or we keep the scan number as an field/parameter....

**Comment by niekdejonge** [comment]
Is scan number always given for query spectra and is it given in the same field independent of machine type?

**Comment by niekdejonge** [comment]
I quickly checked and for mzml files the scan number is not easily stored in the metadata (It is stored as NativeID:"function=2 process=0 scan=1"). 
@justinjjvanderhooft I reread your comment and might have misunderstood. 
Do you mean using an already available scan number in the metadata? Or do you mean basing the scan number on the input order of spectra and storing the scan number as a field/parameter in the metadata of the spectrum? The last option is what I would like to go for. 
One thing I am not 100% sure about is if GNPS uses this same method for determining the #Scan# number in their output... So not sure if this will make the comparison straightforward. Do you know this Justin?

**Comment by florian-huber** [comment]
We could (as you suggested Niek?) also add an ID at the beginning of our analysis. Matchms also provides hashes which we could use after filtering (hashes will change if the spectra change) ?

**Comment by niekdejonge** [comment]
Yes I will add an identifier at the start of our analysis, based on the position in the matchms list (before filtering on number of peaks). I will just add this identifier to the metadata and than read this out at the end of the pipeline.
I think it is best to start numbering at 1 (instead of 0), since this number is mostly relevant for users that are not too familiar with informatics. And I expect mass spectrum instruments and GNPS also starts counting at 1.

**Comment by niekdejonge** [comment]
Regarding the hashes, I do not think we need to use the hashes, since the main purpose is comparing the results with other tools/ the raw data.

**Comment by niekdejonge** [comment]
Solved with #135
