### ISSUE TITLE
Make compatible with new matchms versions

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#136]
The new release of matchms 0.14 is not compatible with MS2Query. Since the releases are building towards matchms 1.0.0, this is not yet a good moment to implement these changes.
Once matchms 1.0.0 is implemented, change MS2Query to be compatible with matchms 1.0.0. 
@florian-huber could you maybe do this by that time? (also a good check to see where workflows will break)

**Comment by florian-huber** [comment]
Yes, I was expacting this or the next release to break a few things. I would keep `matchms <= 0.13.0` for now and do the transition once matchms things are settled.

**Comment by niekdejonge** [comment]
Solved with #139
