### ISSUE TITLE
add classes to sqlite?

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#138]
The current notebook `Generate_predictions_for_test_data.ipynb` asks for the file "ALL_GNPS_210409_positive_processed_annotated_CF_NPC_classes.txt" but is is not clear where this comes from.

I would guess that the class information should also become part of the sqlite database, right?

**Comment by niekdejonge** [comment]
@florian-huber I missed this issue before, but I fully agree that that would make a lot of sense.

**Comment by niekdejonge** [comment]
Solved with #187
