### ISSUE TITLE
upgrade existing GNPS MGF db with new spectra: is that possible ?

### ISSUE THREAD

**Issue by thierrynieus** [iomega/ms2query#141]
Hi all,
thanks for the fantastic software you released. From my side I am trying to add new spectra to the standard db and to train the classifier on the upgraded db. Unfortunately I am encountering errors here and there when I try to work on a joined MGF db.
I suspect I am missing some keys of the db I am adding, so it would great to know if there are minimal requirements to run the entire pipeline?

In the standard GNPS db the keys are: 

['pepmass', 'charge', 'mslevel', 'source_instrument', 'filename', 'seq', 'ionmode', 'organism', 'name', 'pi', 'datacollector', 'smiles', 'inchi', 'inchiaux', 'pubmed', 'submituser', 'libraryquality', 'spectrumid', 'scans', 'compound_name', 'adduct', 'precursor_mz', 'parent_mass', 'inchikey']

in my db I have the following:

['pepmass', 'name', 'ionmode', 'mslevel', 'smiles', 'inchikey', 'compound_name', 'precursor_mz', 'parent_mass']

so I am basically missing:

charge
source_instrument
filename
seq
organism
pi
datacollector
inchi
inchiaux
pubmed
submituser
libraryquality
spectrumid
scans
adduct

I am wondering which of these are really fundamental to run the pipeline. From the output messages I suspect 'spectrumid' could be important, but that one seems to be an ID on the GNPS, so it is not available for the new spectra.

Any suggestion?
Thanks

**Comment by niekdejonge** [comment]
Hi, 

Do I understand it correctly that you tried to manually convert your in house file format to MGF? In that case I expect that something went wrong with this conversion. 

We rely on the matchms software package to load in different file formats (https://github.com/matchms/matchms), so maybe this documentation can also help. The accepted file formats are  JSON, MGF, MSP, MZML, MZXML and Usi.

Actually none of the fields that you mention here are needed for MS2Query. SpectrumID is indeed a GNPS specific field. 

What is the exact error you get when trying to load in your data?

**Comment by niekdejonge** [comment]
Thanks a lot for the extra information! It is now clear to me what went wrong. 

This is indeed an issue on our side. The spectrum ID is indeed required for the creation of a new library (but this shouldn't be the case). I was under the impression that we removed the requirement for a spectrum ID, but now realize we only did so for the query spectra and not for the creation of new libraries. 

I will fix this soon, but it will take a few days (Planned some time to implement this on Friday)
A quick fix is just adding random (but different) spectrum IDs for the spectra you add. 

Sorry for the inconvenience. I will keep you up to date of the progress via this issue.

**Comment by niekdejonge** [comment]
Hi, a start was made with solving the issue, but it is not yet completely finished. I will keep you up to date. (the quick fix of adding spectrum_ids to your spectra should still work).

**Comment by thierrynieus** [comment]
Thanks a loro, I Will perform some tests next week.
Best

Il ven 3 giu 2022, 15:53 Niek de Jonge ***@***.***> ha
scritto:

**Comment by thierrynieus** [comment]
Hi Niek,
I made some progresses adding random spectrumid to the spectra I am adding/appending to the GNPS. This allows to complete all the needed steps to obtain the model. However when I run ms2query with the new model at some point I end up with the message:
`Calculating MS2Deepscore between query embeddings and library embeddings
collecting matches info: 0it [00:05, ?it/s]
Traceback (most recent call last):
  File "/mnt/ms2query_indaco//slurm/plate_test/run_0.py", line 24, in <module>
    ms2library.analog_search_store_in_csv(spectra, fname_out_csv,nr_of_top_analogs_to_save=nr_of_analogs_to_store,minimal_ms2query_metascore=minimal_ms2query_score,additional_metadata_columns=additional_metadata_columns,additional_ms2query_score_columns=additional_ms2query_score_columns)
  File "/mnt/ms2query_indaco/softs/ms2query/lib/python3.8/site-packages/ms2query/ms2library.py", line 255, in analog_search_store_in_csv
    results_df = results_table.export_to_dataframe(nr_of_top_analogs_to_save,
  File "/mnt/ms2query_indaco/softs/ms2query/lib/python3.8/site-packages/ms2query/results_table.py", line 169, in export_to_dataframe
    get_classifier_from_csv_file(self.classifier_csv_file_name,
  File "/mnt/ms2query_indaco/softs/ms2query/lib/python3.8/site-packages/ms2query/utils.py", line 122, in get_classifier_from_csv_file
    classifiers = classifiers_df.loc[
  File "/mnt/ms2query_indaco/softs/ms2query/lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/mnt/ms2query_indaco/softs/ms2query/lib/python3.8/site-packages/pandas/core/indexing.py", line 1181, in _getitem_axis
    elif com.is_bool_indexer(key):
  File "/mnt/ms2query_indaco/softs/ms2query/lib/python3.8/site-packages/pandas/core/common.py", line 144, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values
`
not sure what this means ... (note, I have also updated the file: ALL_GNPS_210409_positive_processed_annotated_CF_NPC_classes.txt with the new spectra).

Any hints?

**Comment by niekdejonge** [comment]
Hi Thierry,

Great to hear adding the spectrum ids solved the issue. 

For this issue I expect that the problem is in the updated ALL_GNPS_210409_positive_processed_annotated_CF_NPC_classes.txt file. To make sure, does it all work well using the old file? On the new model you can just use the old file, it will result in some of the compound classes being left blank, but should not result in errors. 

I expect something went wrong with adding the spectra to the classifier file. It seems like there are Na/NaN s in the new file, causing this problem. Is this indeed the case?

In that case, something might have gone wrong in using the notebook for create_classifier_classifications.ipynb. Could you maybe share the new file generated? Or if this is confidential maybe share if there is a row containing NaNs so I can try to find the origin of this error?

**Comment by niekdejonge** [comment]
Good to hear!

**Comment by niekdejonge** [comment]
In #142 it was made possible to create library files without spectrum ids (using generated IDs instead of the GNPS ids)
and in #146 the library files creation was made a lot easier. Instead of running all the notebooks, now just a small script has to be run. Which will create all the library files needed (tanimoto_scores, sqlite_file and embedding files). This does not include new model training for ms2deepscore and spec2vec, for this you still need to use the code in the notebooks.
