### ISSUE TITLE
install issue on mac M1 chip

### ISSUE THREAD

**Issue by guikool** [iomega/ms2query#147]
Dear developpers,
I've tried to install ms2query on macbook M1 using the dedicated `tensorflow-macos` package. 
This specific installation was ok and run really well: `pip freeze | grep tensorflow`
tensorflow-estimator==2.10.0
tensorflow-macos==2.10.0
tensorflow-metal==0.6.0

Still, `pip install ms2query ` cause a dependency error with tensorflow (which seems to not be recognized).
Here is the readbacks:
```
Collecting ms2query
  Using cached ms2query-0.3.3-py3-none-any.whl (53 kB)
Collecting matchms<=0.13.0,>=0.11.0
  Using cached matchms-0.13.0-py3-none-any.whl (90 kB)
Collecting ms2deepscore
  Using cached ms2deepscore-0.2.3-py3-none-any.whl (43 kB)
Collecting gensim>=4.0.0
  Using cached gensim-4.2.0-cp39-cp39-macosx_11_0_arm64.whl
Collecting ms2query
  Using cached ms2query-0.3.2-py3-none-any.whl (53 kB)
  Using cached ms2query-0.3.1-py3-none-any.whl (51 kB)
  Using cached ms2query-0.3.0-py3-none-any.whl (51 kB)
  Using cached ms2query-0.2.4-py3-none-any.whl (54 kB)
  Using cached ms2query-0.2.3-py3-none-any.whl (54 kB)
  Using cached ms2query-0.2.2-py3-none-any.whl (44 kB)
  Using cached ms2query-0.2.0-py3-none-any.whl (40 kB)
  Using cached ms2query-0.1.0-py3-none-any.whl (6.0 kB)
Collecting streamlit
  Using cached streamlit-1.12.2-py2.py3-none-any.whl (9.1 MB)
Collecting networkx
  Using cached networkx-2.8.6-py3-none-any.whl (2.0 MB)
Collecting plotly
  Using cached plotly-5.10.0-py2.py3-none-any.whl (15.2 MB)
ERROR: Cannot install ms2query==0.1.0, ms2query==0.2.0, ms2query==0.2.2, ms2query==0.2.3, ms2query==0.2.4, ms2query==0.3.0, ms2query==0.3.1, ms2query==0.3.2 and ms2query==0.3.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    ms2query 0.3.3 depends on tensorflow
```
For the record, I was able to install matchms and ms2deepscore using conda arm64 and the tensorflow from conda-forge. But still get an issue when trying to install ms2query

Thanks for your help
G.

**Comment by niekdejonge** [comment]
Dear G., 

I found a similar problem online, but not sure if the solution will solve your issue: https://stackoverflow.com/questions/70480290/not-able-to-install-packages-that-rely-on-tensorflow-on-mac-m1 
This makes me think this is a more common problem with the combination of macos M1 and tensorflow.

We run our tests for MS2Query also on macos systems and this does not cause any issues with tensorflow. 
Does running pip install ms2query in an empty conda environment without tensorflow-macos installed work?

Regards,
Niek

**Comment by guikool** [comment]
Thanks for your reply
Indeed, it causes the same error in an empty conda env. What I don't figure out, is that I was able to install ms2deepscore (which also depend on tensorflow) and this package work pretty well. After intensive browsing on tensorflow on mac M1 chip, it seems to have several issues probably out of the scope of ms2query.
However, using a virtual windows 11 machine solve the problem., so we can close the issue.
Congrats for this beautiful job.
Regards,
G.
