### ISSUE TITLE
Replace analog search return results table with return dataframe

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#185]
The analog search return results table currently returns the entire results table. The rational was other tools could use everything needed and we were not sure what other tools might want to use. 

However, the results table is a difficult object to handle and is very subjective to internal changes that will not be good for stability. 

Instead I propose to just export panda dataframes. This still gives the option in other tools to use the output of MS2Query directly, without the need to first store and load an csv file.

**Comment by florian-huber** [comment]
Seems fine to me. In the long run (once things become more stable) we can always reconsider the output format(s).

**Comment by niekdejonge** [comment]
Solved with #186
