### ISSUE TITLE
Error in applying MS2Query

### ISSUE THREAD

**Issue by anani-a-missinou** [iomega/ms2query#194]
Hi dear developers, 

# Basic information
My operating system: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz, 16.0 GB (15.8 GB usable)

### (ms2query) amissinou@REN-1349-A104$ ls -l
drwxrwxrwx 1 amissinou amissinou 4096 Jun 17 18:40 MS2Query_library
drwxrwxrwx 1 amissinou amissinou 4096 Jun 17 18:36 query_spectra

### (ms2query) amissinou@REN-1349-A104$ ls -l MS2Query_library/
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 ALL_GNPS_210409_positive_processed_annotated_CF_NPC_classes.txt
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 library_GNPS_15_12_2021_ms2ds_embeddings.pickle
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 library_GNPS_15_12_2021_s2v_embeddings.pickle
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 ms2ds_model_GNPS_15_12_2021.hdf5
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 ms2query_library.sqlite
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 ms2query_random_forest_model.onnx
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 spec2vec_model_GNPS_15_12_2021.model
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 spec2vec_model_GNPS_15_12_2021.model.syn1neg.npy
-rwxrwxrwx 1 amissinou amissinou 36770 Jun 17 18:40 spec2vec_model_GNPS_15_12_2021.model.wv.vectors.npy

### (ms2query) amissinou@REN-1349-A104$ ls -l query_spectra/
-rwxrwxrwx 1 amissinou amissinou  400536 Apr 27 07:36 Brassimet_Leaves_NEG_PAXs.mgf
-rwxrwxrwx 1 amissinou amissinou 7540279 Apr 27 07:36 Brassimet_Leaves_POS_PAXs.mgf
-rwxrwxrwx 1 amissinou amissinou  220121 Jun  6 01:31 Brassimet_Roots_Neg_PAXs.mgf
-rwxrwxrwx 1 amissinou amissinou 2863292 Jun  6 01:32 Brassimet_Roots_Pos_PAXs.mgf

# What happened?

### (ms2query) amissinou@REN-1349-A104$ ms2query --spectra .\query_spectra\Brassimet_Roots_Pos_PAXs.mgf --libr
ary .\MS2Query_library --ionmode positive
Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/ms2query/bin/ms2query", line 8, in <module>
    sys.exit(command_line())
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/__init__.py", line 58, in command_line
    args = parser.parse_args()
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/__init__.py", line 25, in path_exists
    assert os.path.exists(path), f"The specified path does not exist, the path given is {path}"
AssertionError: The specified path does not exist, the path given is .query_spectra

### (ms2query) amissinou@REN-1349-A104$ ms2query --spectra ./query_spectra/Brassimet_Roots_Pos_PAXs.mgf --libr
ary ./MS2Query_library/ --ionmode positive
Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/ms2query/bin/ms2query", line 8, in <module>
    sys.exit(command_line())
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/__init__.py", line 78, in command_line
    ms2library = create_library_object_from_one_dir(ms2query_library_files_directory)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/ms2library.py", line 454, in create_library_object_from_one_dir
    return MS2Library(dict_with_file_paths["sqlite"], dict_with_file_paths["s2v_model"],
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/ms2library.py", line 75, in __init__
    self.ms2query_model = load_ms2query_model(ms2query_model_file_name)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/utils.py", line 33, in load_ms2query_model
    return InferenceSession(ms2query_model_file_name)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./MS2Query_library/ms2query_random_forest_model.onnx failed:Protobuf parsing failed.

# Thank you !

**Comment by anani-a-missinou** [comment]
Okay, I am looking forward to hearing from you.

Thank you

**Comment by niekdejonge** [comment]
I was able to reproduce the issue locally, so it was not something you did wrong during installing. I hope to be able to resolve the issue today.

**Comment by niekdejonge** [comment]
It was an issue with the downloading of the model from Zenodo. A recent change uses a different link that did not work, but downloads broken files. I will make a new release soon where this is fixed. So to fix the issue you can upgrade ms2query to the new version. Remove the already downloaded library and download it again using the command line ms2query --library ms2query_library --download --ionmode positive
Alternatively you can also directly download the files from https://zenodo.org/record/7947603

I noticed that you have spectra both in positive and negative ionization modes. Make sure to run them both against the right library. You can download the negative mode library by ms2query --library ms2query_library --download --ionmode negative

**Comment by niekdejonge** [comment]
I have just made a new release 1.2.1. Let me know if this solves the issue for you as well

**Comment by anani-a-missinou** [comment]
Hi, 

I get same error after remove and recreated msquery env


(ms2query) amissinou@REN-1349-A104 /mnt/c/WINDOWS/system32 $ pip install ms2query
Collecting ms2query
  Downloading ms2query-1.2.1-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.0/80.0 kB 1.0 MB/s eta 0:00:00
Collecting matchms<=0.17.0,>=0.14.0 (from ms2query)
  Using cached matchms-0.17.0-py3-none-any.whl (102 kB)
Requirement already satisfied: numpy in /home/amissinou/.local/lib/python3.8/site-packages (from ms2query) (1.24.2)
Collecting spec2vec>=0.6.0 (from ms2query)
  Using cached spec2vec-0.8.0-py3-none-any.whl (34 kB)
Collecting h5py (from ms2query)
  Downloading h5py-3.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 3.7 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in /home/amissinou/.local/lib/python3.8/site-packages/scikit_learn-1.2.2-py3.8-linux-x86_64.egg (from ms2query) (1.2.2)
Collecting ms2deepscore (from ms2query)
  Using cached ms2deepscore-0.4.0-py3-none-any.whl (47 kB)
Collecting gensim>=4.0.0 (from ms2query)
  Using cached gensim-4.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.5 MB)
Collecting pandas<2.0.0,>=1.2.5 (from ms2query)
  Using cached pandas-1.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
Collecting matchmsextras>=0.4.0 (from ms2query)
  Using cached matchmsextras-0.4.1-py3-none-any.whl (26 kB)
Collecting pubchempy (from ms2query)
  Using cached PubChemPy-1.0.4-py3-none-any.whl
Collecting tqdm (from ms2query)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting matplotlib (from ms2query)
  Using cached matplotlib-3.7.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
Collecting skl2onnx (from ms2query)
  Using cached skl2onnx-1.14.1-py2.py3-none-any.whl (292 kB)
Collecting onnxruntime (from ms2query)
  Using cached onnxruntime-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
Collecting tensorflow<2.9 (from ms2query)
  Using cached tensorflow-2.8.4-cp38-cp38-manylinux2010_x86_64.whl (498.0 MB)
Requirement already satisfied: scipy>=1.7.0 in /home/amissinou/.local/lib/python3.8/site-packages (from gensim>=4.0.0->ms2query) (1.10.1)
Collecting smart-open>=1.8.1 (from gensim>=4.0.0->ms2query)
  Using cached smart_open-6.3.0-py3-none-any.whl (56 kB)
Collecting deprecated (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Collecting lxml (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached lxml-4.9.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
Collecting networkx (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting numba>=0.47 (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached numba-0.57.0-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.6 MB)
Collecting pickydict>=0.4.0 (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached pickydict-0.4.0-py3-none-any.whl (6.1 kB)
Collecting pyteomics>=4.2 (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached pyteomics-4.6-py2.py3-none-any.whl (235 kB)
Collecting requests (from matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting python-louvain (from matchmsextras>=0.4.0->ms2query)
  Using cached python_louvain-0.16-py3-none-any.whl
Collecting python-dateutil>=2.8.1 (from pandas<2.0.0,>=1.2.5->ms2query)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Requirement already satisfied: pytz>=2020.1 in /home/amissinou/.local/lib/python3.8/site-packages (from pandas<2.0.0,>=1.2.5->ms2query) (2022.7.1)
Collecting absl-py>=0.4.0 (from tensorflow<2.9->ms2query)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting astunparse>=1.6.0 (from tensorflow<2.9->ms2query)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=1.12 (from tensorflow<2.9->ms2query)
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting gast>=0.2.1 (from tensorflow<2.9->ms2query)
  Using cached gast-0.5.4-py3-none-any.whl (19 kB)
Collecting google-pasta>=0.1.1 (from tensorflow<2.9->ms2query)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting keras-preprocessing>=1.1.1 (from tensorflow<2.9->ms2query)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting libclang>=9.0.1 (from tensorflow<2.9->ms2query)
  Using cached libclang-16.0.0-py2.py3-none-manylinux2010_x86_64.whl (22.9 MB)
Collecting opt-einsum>=2.3.2 (from tensorflow<2.9->ms2query)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting protobuf<3.20,>=3.9.2 (from tensorflow<2.9->ms2query)
  Using cached protobuf-3.19.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Requirement already satisfied: setuptools in /home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages (from tensorflow<2.9->ms2query) (67.7.2)
Collecting six>=1.12.0 (from tensorflow<2.9->ms2query)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting termcolor>=1.1.0 (from tensorflow<2.9->ms2query)
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting typing-extensions>=3.6.6 (from tensorflow<2.9->ms2query)
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting wrapt>=1.11.0 (from tensorflow<2.9->ms2query)
  Using cached wrapt-1.15.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
Collecting tensorboard<2.9,>=2.8 (from tensorflow<2.9->ms2query)
  Using cached tensorboard-2.8.0-py3-none-any.whl (5.8 MB)
Collecting tensorflow-estimator<2.9,>=2.8 (from tensorflow<2.9->ms2query)
  Using cached tensorflow_estimator-2.8.0-py2.py3-none-any.whl (462 kB)
Collecting keras<2.9,>=2.8.0rc0 (from tensorflow<2.9->ms2query)
  Using cached keras-2.8.0-py2.py3-none-any.whl (1.4 MB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow<2.9->ms2query)
  Using cached tensorflow_io_gcs_filesystem-0.32.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow<2.9->ms2query)
  Using cached grpcio-1.54.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
Collecting contourpy>=1.0.1 (from matplotlib->ms2query)
  Using cached contourpy-1.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
Collecting cycler>=0.10 (from matplotlib->ms2query)
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->ms2query)
  Using cached fonttools-4.40.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
Collecting kiwisolver>=1.0.1 (from matplotlib->ms2query)
  Using cached kiwisolver-1.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting packaging>=20.0 (from matplotlib->ms2query)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pillow>=6.2.0 (from matplotlib->ms2query)
  Using cached Pillow-9.5.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Collecting pyparsing>=2.3.1 (from matplotlib->ms2query)
  Downloading pyparsing-3.1.0-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 kB 4.4 MB/s eta 0:00:00
Collecting importlib-resources>=3.2.0 (from matplotlib->ms2query)
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting coloredlogs (from onnxruntime->ms2query)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting sympy (from onnxruntime->ms2query)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Requirement already satisfied: joblib>=1.1.1 in /home/amissinou/.local/lib/python3.8/site-packages/joblib-1.2.0-py3.8.egg (from scikit-learn->ms2query) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/amissinou/.local/lib/python3.8/site-packages/threadpoolctl-3.1.0-py3.8.egg (from scikit-learn->ms2query) (3.1.0)
Collecting onnx>=1.2.1 (from skl2onnx->ms2query)
  Using cached onnx-1.14.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.6 MB)
Collecting onnxconverter-common>=1.7.0 (from skl2onnx->ms2query)
  Using cached onnxconverter_common-1.13.0-py2.py3-none-any.whl (83 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow<2.9->ms2query) (0.40.0)
Collecting zipp>=3.1.0 (from importlib-resources>=3.2.0->matplotlib->ms2query)
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting llvmlite<0.41,>=0.40.0dev0 (from numba>=0.47->matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached llvmlite-0.40.1rc1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.1 MB)
Collecting importlib-metadata (from numba>=0.47->matchms<=0.17.0,>=0.14.0->ms2query)
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
INFO: pip is looking at multiple versions of onnx to determine which version is compatible with other requirements. This could take a while.
Collecting onnx>=1.2.1 (from skl2onnx->ms2query)
  Using cached onnx-1.13.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
  Using cached onnx-1.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
  Using cached onnx-1.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached google_auth-2.20.0-py2.py3-none-any.whl (181 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached Markdown-3.4.3-py3-none-any.whl (93 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0 (from tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting tensorboard-plugin-wit>=1.6.0 (from tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting werkzeug>=0.11.15 (from tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached Werkzeug-2.3.6-py3-none-any.whl (242 kB)
Collecting charset-normalizer<4,>=2 (from requests->matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
Collecting idna<4,>=2.5 (from requests->matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests->matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime->ms2query)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting mpmath>=0.19 (from sympy->onnxruntime->ms2query)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting urllib3<3,>=1.21.1 (from requests->matchms<=0.17.0,>=0.14.0->ms2query)
  Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting MarkupSafe>=2.1.1 (from werkzeug>=0.11.15->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached MarkupSafe-2.1.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.9,>=2.8->tensorflow<2.9->ms2query)
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Installing collected packages: tensorflow-estimator, tensorboard-plugin-wit, pyteomics, pubchempy, mpmath, libclang, keras, flatbuffers, zipp, wrapt, urllib3, typing-extensions, tqdm, termcolor, tensorflow-io-gcs-filesystem, tensorboard-data-server, sympy, smart-open, six, pyparsing, pyasn1, protobuf, pillow, pickydict, packaging, opt-einsum, oauthlib, networkx, MarkupSafe, lxml, llvmlite, kiwisolver, idna, humanfriendly, h5py, grpcio, gast, fonttools, cycler, contourpy, charset-normalizer, certifi, cachetools, absl-py, werkzeug, rsa, requests, python-louvain, python-dateutil, pyasn1-modules, onnx, keras-preprocessing, importlib-resources, importlib-metadata, google-pasta, gensim, deprecated, coloredlogs, astunparse, requests-oauthlib, pandas, onnxruntime, onnxconverter-common, numba, matplotlib, markdown, google-auth, skl2onnx, matchms, google-auth-oauthlib, tensorboard, spec2vec, tensorflow, matchmsextras, ms2deepscore, ms2query
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
biodendro 0.0.3 requires xlrd, which is not installed.
biodendro 0.0.3 requires xlsxwriter, which is not installed.
canopus 0.0.1 requires jupyter>=1.0.0, which is not installed.
Successfully installed MarkupSafe-2.1.3 absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.1 certifi-2023.5.7 charset-normalizer-3.1.0 coloredlogs-15.0.1 contourpy-1.1.0 cycler-0.11.0 deprecated-1.2.14 flatbuffers-23.5.26 fonttools-4.40.0 gast-0.5.4 gensim-4.3.1 google-auth-2.20.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.54.2 h5py-3.9.0 humanfriendly-10.0 idna-3.4 importlib-metadata-6.7.0 importlib-resources-5.12.0 keras-2.8.0 keras-preprocessing-1.1.2 kiwisolver-1.4.4 libclang-16.0.0 llvmlite-0.40.1rc1 lxml-4.9.2 markdown-3.4.3 matchms-0.17.0 matchmsextras-0.4.1 matplotlib-3.7.1 mpmath-1.3.0 ms2deepscore-0.4.0 ms2query-1.2.1 networkx-3.1 numba-0.57.0 oauthlib-3.2.2 onnx-1.12.0 onnxconverter-common-1.13.0 onnxruntime-1.15.1 opt-einsum-3.3.0 packaging-23.1 pandas-1.5.3 pickydict-0.4.0 pillow-9.5.0 protobuf-3.19.6 pubchempy-1.0.4 pyasn1-0.5.0 pyasn1-modules-0.3.0 pyparsing-3.1.0 pyteomics-4.6 python-dateutil-2.8.2 python-louvain-0.16 requests-2.31.0 requests-oauthlib-1.3.1 rsa-4.9 six-1.16.0 skl2onnx-1.14.1 smart-open-6.3.0 spec2vec-0.8.0 sympy-1.12 tensorboard-2.8.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.8.4 tensorflow-estimator-2.8.0 tensorflow-io-gcs-filesystem-0.32.0 termcolor-2.3.0 tqdm-4.65.0 typing-extensions-4.6.3 urllib3-1.26.16 werkzeug-2.3.6 wrapt-1.15.0 zipp-3.15.0
(ms2query) amissinou@REN-1349-A104 /mnt/c/WINDOWS/system32 $ cd ../../../d/Parts/DATA/Metabolomics/rawData/BRASSIMET/Batch_1/Diversity\ of\ Brassica\ PAXs/Supporting_data/Molecular\ networking/MS2Query/
(ms2query) amissinou@REN-1349-A104 /mnt/d/Parts/DATA/Metabolomics/rawData/BRASSIMET/Batch_1/Diversity of Brassica PAXs/Supporting_data/Molecular networking/MS2Query $ lq -l
lq: command not found
(ms2query) amissinou@REN-1349-A104 /mnt/d/Parts/DATA/Metabolomics/rawData/BRASSIMET/Batch_1/Diversity of Brassica PAXs/Supporting_data/Molecular networking/MS2Query $ ls -l
total 0
drwxrwxrwx 1 amissinou amissinou 4096 Jun 17 18:40 MS2Query_library
drwxrwxrwx 1 amissinou amissinou 4096 Jun 19 14:59 query_spectra
(ms2query) amissinou@REN-1349-A104 /mnt/d/Parts/DATA/Metabolomics/rawData/BRASSIMET/Batch_1/Diversity of Brassica PAXs/Supporting_data/Molecular networking/MS2Query $ ms2query --spectra ./query_spectra/Brassimet_Roots_Pos_PAXs.mgf --library ./MS2Query_library/ --ionmode positive
Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/ms2query/bin/ms2query", line 8, in <module>
    sys.exit(command_line())
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/__init__.py", line 78, in command_line
    ms2library = create_library_object_from_one_dir(ms2query_library_files_directory)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/ms2library.py", line 454, in create_library_object_from_one_dir
    return MS2Library(dict_with_file_paths["sqlite"], dict_with_file_paths["s2v_model"],
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/ms2library.py", line 75, in __init__
    self.ms2query_model = load_ms2query_model(ms2query_model_file_name)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/utils.py", line 33, in load_ms2query_model
    return InferenceSession(ms2query_model_file_name)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./MS2Query_library/ms2query_random_forest_model.onnx failed:Protobuf parsing failed.
(ms2query) amissinou@REN-1349-A104 /mnt/d/Parts/DATA/Metabolomics/rawData/BRASSIMET/Batch_1/Diversity of Brassica PAXs/Supporting_data/Molecular networking/MS2Query $ ms2query --spectra .\query_spectra --library .\MS2Query_library --ionm
ode positive
Traceback (most recent call last):
  File "/home/amissinou/miniconda3/envs/ms2query/bin/ms2query", line 8, in <module>
    sys.exit(command_line())
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/__init__.py", line 58, in command_line
    args = parser.parse_args()
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/home/amissinou/miniconda3/envs/ms2query/lib/python3.8/site-packages/ms2query/__init__.py", line 25, in path_exists
    assert os.path.exists(path), f"The specified path does not exist, the path given is {path}"
AssertionError: The specified path does not exist, the path given is .query_spectra

**Comment by niekdejonge** [comment]
Could you delete the library that you downloaded before in the folder MS2Query_library and download the correct files using the command ms2query --library ms2query_library --download --ionmode positive

**Comment by anani-a-missinou** [comment]
Hi, 

## I well done on my files, however, I have this message for all metabolites.

2023-06-22 19:23:00,536:WARNING:matchms:add_compound_name:No compound name found in metadata.
2023-06-22 19:23:00,537:WARNING:matchms:interpret_pepmass:Overwriting existing precursor_mz 458.8559 with new one: 458.8559
Predicting matches for query spectra: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 948/948 [43:18<00:00,  2.74s/it]
Results stored in query_spectra/results/Brassimet_Roots_Pos_PAXs.csv

## Moreover, by analyzing the results, I was strange by the fact that many metabolites mean from bacteria. Do you test your tool on plant data? 

## From what 'ms2query_model_prediction' threshold can I assume that the annotation can be correct?, In order to manually check a short list of metabolites, especially for fewer metabolites having precursor_mz_difference lower than 0.01 (because I used UHR-QqTOF Impact II Bruker Daltonics). Is this threshold identical for less mass above 500Da and greater than 850 Da?

Thank you for your help

**Comment by niekdejonge** [comment]
Good to hear! Those warnings can be ignored. It seems like it did run correctly! 

About the results. We mainly got results back from collaborators working with bacteria, fungi or human samples so far. The quality of predictions will mainly dependent on how many closely related metabolites are in the library that is used by MS2Query. 

For interpretation of the results there is no strict threshold. I would not look at matches with a score below 0.6. Scores above 0.8 are very often good analogues or exact matches. In between 0.6 and 0.7 you have to be a bit more critical.
