### ISSUE TITLE
ONNX issue

### ISSUE THREAD

**Issue by eeko-kon** [iomega/ms2query#208]
Hi Niek :) 

I am suddenly getting this error:

`ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)`

Have you encountered this? 

Relevant issue I found online: 
https://github.com/microsoft/onnxruntime/issues/17631

**Comment by niekdejonge** [comment]
Hi Efi, 

Sorry for the late response, I was away for holidays. 

Thanks for sharing!
This indeed seems to be the issue with onnxruntime that you already shared. I expect the quick fix is setting ONNXRuntime to <1.16. So I will do this for the MS2Query requirements, I hope that fixes the issue. 

Let me know if this is still an issue when using an older version of onnxruntime.

**Comment by eeko-kon** [comment]
thank you Niek! Amazing! FYI the 1.2.3 version is not available through pip yet

**Comment by niekdejonge** [comment]
Ah sorry about that, was getting started up again after the holidays... Now version 1.2.4 contains the change. (1.2.3 has been removed)

**Comment by eeko-kon** [comment]
So fast, thank youuuu ! :))

**Comment by poshul** [comment]
FYI, this is fixed as of ONNX 1.16.1, and <1.17 are not available in PIP any more, so it might be worthwhile to remove the restriction.
