### ISSUE TITLE
pip install ms2query failed (This error originates from a subprocess, and is likely not a problem with pip.)

### ISSUE THREAD

**Issue by TOTOZAFY** [iomega/ms2query#239]
Collecting ms2query
  Using cached ms2query-1.4.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: matchms>=0.24.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2query) (0.24.4)
Requirement already satisfied: numpy in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2query) (1.24.4)
Collecting spec2vec>=0.6.0 (from ms2query)
  Using cached spec2vec-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting h5py (from ms2query)
  Using cached h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting pyarrow (from ms2query)
  Using cached pyarrow-16.1.0-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: scikit-learn in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2query) (1.4.2)
Collecting ms2deepscore==0.5.0 (from ms2query)
  Using cached ms2deepscore-0.5.0-py3-none-any.whl.metadata (7.5 kB)
Collecting gensim>=4.0.0 (from ms2query)
  Using cached gensim-4.3.2-cp311-cp311-win_amd64.whl.metadata (8.5 kB)
Requirement already satisfied: pandas in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2query) (2.2.2)
Requirement already satisfied: tqdm in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2query) (4.66.4)
Requirement already satisfied: matplotlib in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2query) (3.7.2)
Collecting skl2onnx (from ms2query)
  Using cached skl2onnx-1.16.0-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting onnxruntime<1.16 (from ms2query)
  Using cached onnxruntime-1.15.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: numba in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from ms2deepscore==0.5.0->ms2query) (0.57.1)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: scipy>=1.7.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from gensim>=4.0.0->ms2query) (1.10.1)
Collecting smart-open>=1.8.1 (from gensim>=4.0.0->ms2query)
  Using cached smart_open-7.0.4-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: deprecated<2.0.0,>=1.2.14 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (1.2.14)
Requirement already satisfied: lxml<5.0.0,>=4.9.3 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (4.9.4)
Requirement already satisfied: networkx<4.0,>=3.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (3.3)
Requirement already satisfied: pickydict<0.5.0,>=0.4.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (0.4.0)
Requirement already satisfied: pillow!=9.4.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (10.3.0)
Requirement already satisfied: pubchempy in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (1.0.4)
Requirement already satisfied: pyteomics<5.0,>=4.6 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (4.7.2)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (6.0.1)
Requirement already satisfied: rdkit<2024.0.0,>=2023.3.2 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (2023.9.6)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (2.31.0)
Requirement already satisfied: sparsestack<0.5.0,>=0.4.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matchms>=0.24.0->ms2query) (0.4.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (24.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from matplotlib->ms2query) (2.9.0.post0)
Collecting coloredlogs (from onnxruntime<1.16->ms2query)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime<1.16->ms2query)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Collecting protobuf (from onnxruntime<1.16->ms2query)
  Using cached protobuf-5.26.1-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Requirement already satisfied: sympy in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from onnxruntime<1.16->ms2query) (1.12)
Requirement already satisfied: pytz>=2020.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from pandas->ms2query) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from pandas->ms2query) (2024.1)
Requirement already satisfied: colorama in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from tqdm->ms2query) (0.4.6)
Requirement already satisfied: joblib>=1.2.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from scikit-learn->ms2query) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from scikit-learn->ms2query) (3.5.0)
Collecting onnx>=1.2.1 (from skl2onnx->ms2query)
  Using cached onnx-1.16.0-cp311-cp311-win_amd64.whl.metadata (16 kB)
Collecting onnxconverter-common>=1.7.0 (from skl2onnx->ms2query)
  Using cached onnxconverter_common-1.14.0-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from deprecated<2.0.0,>=1.2.14->matchms>=0.24.0->ms2query) (1.16.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from numba->ms2deepscore==0.5.0->ms2query) (0.40.1)
Collecting protobuf (from onnxruntime<1.16->ms2query)
  Using cached protobuf-3.20.2-py2.py3-none-any.whl.metadata (720 bytes)
Requirement already satisfied: six>=1.5 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from python-dateutil>=2.7->matplotlib->ms2query) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from requests<3.0.0,>=2.31.0->matchms>=0.24.0->ms2query) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from requests<3.0.0,>=2.31.0->matchms>=0.24.0->ms2query) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from requests<3.0.0,>=2.31.0->matchms>=0.24.0->ms2query) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from requests<3.0.0,>=2.31.0->matchms>=0.24.0->ms2query) (2024.2.2)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime<1.16->ms2query)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: mpmath>=0.19 in c:\users\jean\miniconda\envs\matchms\lib\site-packages (from sympy->onnxruntime<1.16->ms2query) (1.3.0)
Collecting tensorflow-intel==2.16.1 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Collecting absl-py>=1.0.0 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached gast-0.5.4-py3-none-any.whl.metadata (1.3 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting ml-dtypes~=0.3.1 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached ml_dtypes-0.3.2-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.16.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
INFO: pip is looking at multiple versions of tensorflow-intel to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.15.1-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Collecting tensorflow-intel==2.15.1 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.15.1-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting tensorflow-intel==2.15.0 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting ml-dtypes~=0.2.0 (from tensorflow-intel==2.15.0->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached ml_dtypes-0.2.0-cp311-cp311-win_amd64.whl.metadata (20 kB)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.14.1-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.14.1 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.14.1-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.14.0 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.13.1-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting tensorflow-intel==2.13.1 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.13.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-intel==2.13.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting numpy (from ms2query)
  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.13.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting tensorflow-intel==2.13.0 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.13.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.12.1-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting tensorflow-intel==2.12.1 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.12.1-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting jax>=0.3.15 (from tensorflow-intel==2.12.1->tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached jax-0.4.28-py3-none-any.whl.metadata (23 kB)
INFO: pip is still looking at multiple versions of tensorflow-intel to determine which version is compatible with other requirements. This could take a while.
Collecting tensorflow (from ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow-2.12.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting tensorflow-intel==2.12.0 (from tensorflow->ms2deepscore==0.5.0->ms2query)
  Using cached tensorflow_intel-2.12.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Collecting sparsestack<0.5.0,>=0.4.1 (from matchms>=0.24.0->ms2query)
  Using cached sparsestack-0.4.1-py3-none-any.whl.metadata (5.0 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting scipy>=1.7.0 (from gensim>=4.0.0->ms2query)
  Using cached scipy-1.10.1-cp311-cp311-win_amd64.whl.metadata (58 kB)
  Using cached scipy-1.10.0-cp311-cp311-win_amd64.whl.metadata (58 kB)
  Using cached scipy-1.9.3-cp311-cp311-win_amd64.whl.metadata (58 kB)
  Using cached scipy-1.9.2-cp311-cp311-win_amd64.whl.metadata (58 kB)
  Using cached scipy-1.9.1.tar.gz (42.0 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

ERROR START IN THIS STEP
error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  [55 lines of output]
  The Meson build system
  Version: 0.62.2
  Source dir: [C:\Users\Jean\AppData\Local\Temp\pip-install-2n7u2xrr\scipy_c4ddaa89fd5c484285268f848d94d2b3](file:///C:/Users/Jean/AppData/Local/Temp/pip-install-2n7u2xrr/scipy_c4ddaa89fd5c484285268f848d94d2b3)
  Build dir: [C:\Users\Jean\AppData\Local\Temp\pip-install-2n7u2xrr\scipy_c4ddaa89fd5c484285268f848d94d2b3\.mesonpy-nd1ej9w9\build](file:///C:/Users/Jean/AppData/Local/Temp/pip-install-2n7u2xrr/scipy_c4ddaa89fd5c484285268f848d94d2b3/.mesonpy-nd1ej9w9/build)
  Build type: native build
  Project name: SciPy
  Project version: 1.9.1
  WARNING: Failed to activate VS environment: Could not find [C:\Program](file:///C:/Program) Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
  
  .[.\..\meson.build:1:0](http://localhost:8889/lab/meson.build#line=0): ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
  The following exception(s) were encountered:
  Running "icl " gave "[WinError 2] Le fichier spécifié est introuvable"
  Running "cl /?" gave "[WinError 2] Le fichier spécifié est introuvable"
  Running "cc --version" gave "[WinError 2] Le fichier spécifié est introuvable"
  Running "gcc --version" gave "[WinError 2] Le fichier spécifié est introuvable"
  Running "clang --version" gave "[WinError 2] Le fichier spécifié est introuvable"
  Running "clang-cl /?" gave "[WinError 2] Le fichier spécifié est introuvable"
  Running "pgcc --version" gave "[WinError 2] Le fichier spécifié est introuvable"
  
  A full log can be found at [C:\Users\Jean\AppData\Local\Temp\pip-install-2n7u2xrr\scipy_c4ddaa89fd5c484285268f848d94d2b3\.mesonpy-nd1ej9w9\build\meson-logs\meson-log.txt](file:///C:/Users/Jean/AppData/Local/Temp/pip-install-2n7u2xrr/scipy_c4ddaa89fd5c484285268f848d94d2b3/.mesonpy-nd1ej9w9/build/meson-logs/meson-log.txt)
  + meson setup --native-file=[C:\Users\Jean\AppData\Local\Temp\pip-install-2n7u2xrr\scipy_c4ddaa89fd5c484285268f848d94d2b3\.mesonpy-native-file.ini](file:///C:/Users/Jean/AppData/Local/Temp/pip-install-2n7u2xrr/scipy_c4ddaa89fd5c484285268f848d94d2b3/.mesonpy-native-file.ini) -Ddebug=false -Doptimization=2 --prefix=[C:\Users\Jean\miniconda\envs\matchms](file:///C:/Users/Jean/miniconda/envs/matchms) [C:\Users\Jean\AppData\Local\Temp\pip-install-2n7u2xrr\scipy_c4ddaa89fd5c484285268f848d94d2b3](file:///C:/Users/Jean/AppData/Local/Temp/pip-install-2n7u2xrr/scipy_c4ddaa89fd5c484285268f848d94d2b3) [C:\Users\Jean\AppData\Local\Temp\pip-install-2n7u2xrr\scipy_c4ddaa89fd5c484285268f848d94d2b3\.mesonpy-nd1ej9w9\build](file:///C:/Users/Jean/AppData/Local/Temp/pip-install-2n7u2xrr/scipy_c4ddaa89fd5c484285268f848d94d2b3/.mesonpy-nd1ej9w9/build)
  Traceback (most recent call last):
    File "[C:\Users\Jean\miniconda\envs\matchms\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353](file:///C:/Users/Jean/miniconda/envs/matchms/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=352), in <module>
      main()
    File "[C:\Users\Jean\miniconda\envs\matchms\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335](file:///C:/Users/Jean/miniconda/envs/matchms/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=334), in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "[C:\Users\Jean\miniconda\envs\matchms\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118](file:///C:/Users/Jean/miniconda/envs/matchms/Lib/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py#line=117), in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 969](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=968), in get_requires_for_build_wheel
      with _project(config_settings) as project:
    File "[C:\Users\Jean\miniconda\envs\matchms\Lib\contextlib.py", line 137](file:///C:/Users/Jean/miniconda/envs/matchms/Lib/contextlib.py#line=136), in __enter__
      return next(self.gen)
             ^^^^^^^^^^^^^^
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 948](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=947), in _project
      with Project.with_temp_working_dir(
    File "[C:\Users\Jean\miniconda\envs\matchms\Lib\contextlib.py", line 137](file:///C:/Users/Jean/miniconda/envs/matchms/Lib/contextlib.py#line=136), in __enter__
      return next(self.gen)
             ^^^^^^^^^^^^^^
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 777](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=776), in with_temp_working_dir
      yield cls(source_dir, tmpdir, build_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 682](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=681), in __init__
      self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 713](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=712), in _configure
      self._meson(
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 696](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=695), in _meson
      return self._proc('meson', *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "[C:\Users\Jean\AppData\Local\Temp\pip-build-env-w1llbkt9\overlay\Lib\site-packages\mesonpy\__init__.py", line 691](file:///C:/Users/Jean/AppData/Local/Temp/pip-build-env-w1llbkt9/overlay/Lib/site-packages/mesonpy/__init__.py#line=690), in _proc
      subprocess.check_call(list(args))
    File "[C:\Users\Jean\miniconda\envs\matchms\Lib\subprocess.py", line 413](file:///C:/Users/Jean/miniconda/envs/matchms/Lib/subprocess.py#line=412), in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=[C:\\Users\\Jean\\AppData\\Local\\Temp\\pip-install-2n7u2xrr\\scipy_c4ddaa89fd5c484285268f848d94d2b3\\.mesonpy-native-file.ini](file:///C://Users//Jean//AppData//Local//Temp//pip-install-2n7u2xrr//scipy_c4ddaa89fd5c484285268f848d94d2b3//.mesonpy-native-file.ini)', '-Ddebug=false', '-Doptimization=2', '--prefix=[C:\\Users\\Jean\\miniconda\\envs\\matchms](file:///C://Users//Jean//miniconda//envs//matchms)', '[C:\\Users\\Jean\\AppData\\Local\\Temp\\pip-install-2n7u2xrr\\scipy_c4ddaa89fd5c484285268f848d94d2b3](file:///C://Users//Jean//AppData//Local//Temp//pip-install-2n7u2xrr//scipy_c4ddaa89fd5c484285268f848d94d2b3)', '[C:\\Users\\Jean\\AppData\\Local\\Temp\\pip-install-2n7u2xrr\\scipy_c4ddaa89fd5c484285268f848d94d2b3\\.mesonpy-nd1ej9w9\\build](file:///C://Users//Jean//AppData//Local//Temp//pip-install-2n7u2xrr//scipy_c4ddaa89fd5c484285268f848d94d2b3//.mesonpy-nd1ej9w9//build)']' returned non-zero exit status 1.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

WHAT CAN I DO TO FIX THIS PROBLEM ?

**Comment by niekdejonge** [comment]
This is not an issue with MS2Query specific, but with installing Scipy. Based on some quick googling, you likely are working on a 32 bit installation of python, this is not supported by Scipy anymore. It then tries to compile it, which requires a lot of other stuff (C++ compilers and others) which you likely don't have installed. Got it from this other issue: https://github.com/danielgatis/rembg/issues/377 So I think the best fix is to reinstall python, but use the 64 bit installation. But maybe do a bit more googling first, since I did not see this issue before myself.
