### ISSUE TITLE
Automatic zenodo upload failing

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#242]
The automatic zenodo upload fails, likely due to incompatible citation file. As mentioned here: https://github.com/zenodo/zenodo/issues/2515 

Florian used https://citation-file-format.github.io/cff-initializer-javascript/#/ to convert the citation to an up to date format for matchms.

**Comment by florian-huber** [comment]
Seems to be fixed with an update of `CITATION.cff` (made using [CFFINIT](https://citation-file-format.github.io/cff-initializer-javascript/#/)).

**Comment by florian-huber** [comment]
Just updated the `CITATION.cff`. Should now work with the next release.

What could be still added is: `preferred-citation:` entry to cite the actual article.
