### ISSUE TITLE
Move (most) library information to database

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#35]
In general I think we will have to move the memory expensive stuff that is not needed for fast execution into databases. 

One database for the pre-calculated tanimoto scores, and one database for the library spectra. We would only have to keep an array of spectrum embeddings for all library spectra in memory (that would be a numpy array of size <100,000 x 300). This is all we need to compute the new Spec2Vec scores for the first candidate sorting.  Only then will the required 10 to 50 Tanimoto scores and full spectra be loaded from the databases. That should make it much more lightweight.

**Comment by niekdejonge** [comment]
This is implemented with #56. 

The tanimoto scores and library spectra are stored in a sqlite database file in 3 tables. 
One table stores the sqlite spectra and their metadata.
The tanimoto scores are stored in one table and are labeled with identifiers (integers). To know which identifier corresponds to which number a third table is used which stores the relationship between inchikey and identifier. 
Functions to retrieve the information from the database have been written as well. 

The storing and loading from the database still has to be integrated with the rest of the functions/app.
