### ISSUE TITLE
Sometimes all streamlit widgets get reset when adjusting a widget inside another widget

### ISSUE THREAD

**Issue by louwenjjr** [iomega/ms2query#45]
Reminiscent of https://discuss.streamlit.io/t/the-button-inside-a-button-seems-to-reset-the-whole-app-why/1051

Possible solution is to use something like this SessionState object https://gist.github.com/tvst/faf057abbedaccaa70b48216a1866cdd

**Comment by florian-huber** [comment]
I indeed also found this to be a problem that could become annoying very quickly.
Part of this could also be solved by processing the network adjustments in javascript (#34). 
(meaning that one way or the other we should get rid of this ;) )

**Comment by RaffalShafiei** [comment]
I also faced this issue and it is very annoying. is there any other way to avoid this rather than using SessionState?

**Comment by florian-huber** [comment]
This is outdated since we (currently) no longer work on a streamlit based app. Future app development will happen here: https://github.com/iomega/ms2query-app
