### ISSUE TITLE
Implement sqlite (or similar) database for loading/storing spectra

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#50]
See also #46

**Comment by florian-huber** [comment]
The idea here is to save matchms-type lists of spectrum objects in a local database.
For instance using sqlite --> see e.g. here: https://www.pythonforthelab.com/blog/storing-data-with-sqlite/

For prototyping the data from our matchms tutorial would work fine I think (1267 spectra):
```python
import os
import numpy as np
from matchms.importing import load_from_mgf

path_data = os.path.join(os.path.dirname(os.getcwd()), "data") #"..." enter your pathname to the downloaded file
file_mgf = os.path.join(path_data, "GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf")
spectrums = list(load_from_mgf(file_mgf))
```

**Comment by florian-huber** [comment]
This will be solved by PR #53. The discussion on further optimizing this procedure will continue in #54.

**Comment by niekdejonge** [comment]
Pull request #56 optimized this for large files, tested for 100.000 spectra.

**Comment by niekdejonge** [comment]
Discussion about implementing this functionality will continue under #46.
