### ISSUE TITLE
Monitor test coverage and inspect code quality

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#58]
Best seems to add Sonarcloud.

**Comment by florian-huber** [comment]
I think I have only access to the `matchms` organization on sonarcloud, but not `iomega`. Do you have access @sverhoeven (and can you add the necessary token or give me rights)?

**Comment by sverhoeven** [comment]
Done, members of sonarcloud org are now synced with GitHub.

**Comment by florian-huber** [comment]
Perfect, thanks a lot Stefan!

**Comment by florian-huber** [comment]
Sonarcloud has now been added to the github actions in #62
