### ISSUE TITLE
Choose different storage type for pickle

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#67]
Currently pickle is used to store most files needed for ms2query (like embeddings). However pickle has some downsides, like security issues. Compare pickle to other alternatives and change to a good alternative storage method.

**Comment by niekdejonge** [comment]
An option might be using SQLite to also store the embeddings (possibly instead of peaks, see #76) and loading these into memory when creating a MS2Library class, so it still has quick performance. A benefit for this would be, having only one file to download for a new library, making it clearer for the user and having less risk of mismatching a SQLite file with an embeddings file, which would lead to unexpected behavior. 

**Important** Tested the speed of loading all spectra from SQLite and this takes about a minute for 177278 spectra. This is too long (loading a pickled file into memory is almost instant). There might be more efficient ways of loading a complete sqlite table into memory, that would make this a good solution, but I did not quickly find a solution for this.

**Comment by justinjjvanderhooft** [comment]
I think storing the embeddings (as well) in SQLite makes sense - loading those should be much quicker than a minute, right?

**Comment by niekdejonge** [comment]
An error occurred after pandas 1.3 was released. The problem occurred when loading in pickled panda files. Loading in panda files pickled when an older version of pandas was in use, results in an error.
Since all test files (and other previously created files for the case studies) are of an older pandas version, this would mean these would all have to be converted to the new pandas version, before MS2Query is compatible with the new pandas release.

Since this problem will keep arising with new releases of pandas it might be best to completely remove the use of pickle and choose a different file storing method.
