### ISSUE TITLE
swap branches once development is 'ready'

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#75]
Once the new version in `development` is working we have to decide how to merge things. I guess options are:
- merge into `main` --> will cost work to refactor the streamlit app
- move the streamlit app to a different repo (`ms2query_app_prototype`)
- move the streamlit app to a different branch (`ms2query_app_prototype`) and make `development` --> `main`

**Comment by niekdejonge** [comment]
In #90 the development branch is merged into the main branch. The old version of MS2Query, developed by Joris Louwen in 2020 is moved to the branch ms2query_app_prototype.
